export const routeNames = {
  general: {
    profiling: "/profiling",
    signin: "/profiling/signin",
    signup: "/profiling/signup",
    forgetPassword: "/profiling/forget-password",
    newPassword: "/profiling/new-password",
    dashboard: "/",
    shops: "/shops/:type",
    activeShops: "/shops/Active",
    inactiveShops: "/shops/Inactive",
    pendingShops: "/shops/Pending",
    addShop: "/shops/add-shop",
    viewShop: "/shops/view/:id",
    drops: "/drops/:type",
    inactiveDrops: "/drops/Inactive",
    activeDrops: "/drops/Active",
    pendingDrops: "/drops/Pending",
    addDrop1: "/drops/add-drop-step-1",
    addDrop2: "/drops/add-drop-step-2",
    addDropSpot: "/drops/add-drop-Spot",
    claimedDrops: "/drops/Claimed",
    users: "/users",
    settings: "/settings",
  },
};
